server:
  port: 8081
spring:
  cloud:     config:
      server:
        git:
          default-label: config-service
          uri: https://github.com/critBus/prueba_microservicios
          search-paths: config-data
  application:
    name: config-service