server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microserviciowastemanager
          uri: lb://microserviciowastemanager
          predicates:
            - Path=/waste/**
        - id: microserviciowastemanageraddres
          uri: lb://microserviciowastemanageraddres
          predicates:
            - Path=/address/**
        